name: artifacts build 

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # Update references
      - name: Git Submodule Update
        run: |
          # git pull --recurse-submodules artifact_builder
          git submodule update --remote --recursive
          
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
  
      - name: install python packages
        run: |
          cd artifact_builder &&\
          python -m pip install --upgrade pip &&\
          pip install -r requirements.txt
  
      - name: execute artifact_builder 
        run: python artifact_builder -D sql -O index.json -E mysql
      
